version: '2'
services:
    db:
        image: mongo
    api:
        build: ./presence-api
        ports: 
            - "3000:3000"
        depends_on:
            - "db"
        env_file:
            - "./presence-api/env/${NODE_ENV}.env"
    web:
        build: ./presence-web
        ports: 
            - "8000:8000"
        env_file:
            - "./presence-web/env/${NODE_ENV}.env"
